aa: rand-m9-mstd0.5-inc1
amp: true
apex_amp: false
aug_repeats: 0
aug_splits: 0
batch_size: 16
bce_loss: false
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 1
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 0
crop_pct: 1.0
cutmix: 0.0
cutmix_minmax: null
data_dir: /mnt/tmp/ilsvrc2012
decay_epochs: 100
decay_rate: 0.1
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.6
epoch_repeats: 0.0
epochs: 30
eval_metric: top1
experiment: ''
gp: null
hflip: 0.5
img_size: 384
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
local_rank: 0
log_interval: 100
log_wandb: false
lr: 0.00002
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-06
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: rdnet_large
model_ema: false
model_ema_decay: 0.9997
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: null
opt: adamw
opt_betas: null
opt_eps: null
output: ''
patience_epochs: 10
pin_mem: true
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.25
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 0
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: true
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_epochs: 5
warmup_lr: 1.0e-6
weight_decay: 0.00000001
workers: 8
bce_target_thresh: null
aot_autograd: false
grad_accum_steps: 8
layer_decay: 0.7
head_init_scale: 0.001